DROP TABLE db_water.grain_dropdown;
CREATE TABLE db_water.grain_dropdown (id bigint, name varchar(20), pH decimal(4,2), type integer);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (1, '2-ROW', 5.70, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (2, '6-ROW', 5.79, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (3, 'MARIS OTTER', 5.77, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (4, 'MUNICH', 5.43, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (5, 'PILSNER', 5.75, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (6, 'WHEAT', 6.04, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (7, 'VIENNA', 5.56, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (8, 'OTHER', 5.70, 1);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (9, 'CRYSTAL', null, 2);
INSERT INTO db_water.grain_dropdown (id, name, pH, type) VALUES (10, 'ROASTED', 5.70, 3);